### PR TITLE
fix: typo about page text

### PR DESCRIPTION
**Pull request by ronthetech**
## Changes

Fixed a typo, Changed "Andorid" to "Android"

## Screenshots

typo1
fix

### CODE REVIEW

**Comment by aleksa-codes** [comment]
@ronthetech Appreciate your attention to detail. I've gone ahead and merged the PR, so the typo has now been fixed. Thanks!

**Comment by ronthetech** [comment]
No problem! I really love your design by the way, your app looks and feels amazing💯

**Comment by aleksa-codes** [comment]
> No problem! I really love your design by the way, your app looks and feels amazing💯

@ronthetech Thank you so much 😄 I recommend checking out daisyUI component library by @saadeghi

**Comment by ronthetech** [comment]
I will definitely check them out, thanks!

**Pull request merged**
